# Generated by Django 2.2.2 on 2019-06-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates_api', '0002_auto_20190616_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
