# Generated by Django 2.2.2 on 2019-06-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates_api', '0003_auto_20190616_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
