# Generated by Django 2.2.2 on 2019-06-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates_api', '0004_auto_20190616_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='day',
        ),
    ]
