# Generated by Django 2.2.2 on 2019-06-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates_api', '0005_remove_price_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='day',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
