# Generated by Django 2.2.2 on 2019-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates_api', '0006_price_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
